### ISSUE TITLE
/solutions/index E2E delivery

### ISSUE THREAD

**Issue by basecode** [hlxsites/bitdefender#39]
-  [ ] plans cards - All-in-One Plans. #7
<img width="1368" alt="Screenshot 2023-07-31 at 11 57 46" src="https://github.com/hlxsites/bitdefender/assets/166901/b231cda0-16a6-440f-a8f8-4c59f352d7c2">

- [ ] solutions cards - Device Security #7
<img width="1368" alt="Screenshot 2023-07-31 at 11 58 26" src="https://github.com/hlxsites/bitdefender/assets/166901/d91d6e8c-12e1-4122-b5cb-1436780eaf2c">

- [ ] solutions cards - Device Security for Mac & mobile #7
<img width="1353" alt="Screenshot 2023-07-31 at 12 00 22" src="https://github.com/hlxsites/bitdefender/assets/166901/4d4fb944-11a0-4a98-af2b-75da10a7ec57">

- [ ] plans cards - Privacy solutions #7
<img width="1353" alt="Screenshot 2023-07-31 at 12 00 22" src="https://github.com/hlxsites/bitdefender/assets/166901/ddc66b9b-5227-4940-9fc3-37d4e0ad477f">

- [x] barchart render
<img width="1373" alt="Screenshot 2023-07-31 at 12 01 19" src="https://github.com/hlxsites/bitdefender/assets/166901/1e167c43-84d1-4cab-92f7-dca34253faf1">

- [x] Terms of use
<img width="1386" alt="Screenshot 2023-07-31 at 12 01 33" src="https://github.com/hlxsites/bitdefender/assets/166901/a17294a5-f5d5-45a3-9b61-8faa404c5d81">

**Comment by andreibogdan** [comment]
New components were identified and issues created for them.
