### ISSUE TITLE
Set up WebSDK

### ISSUE THREAD

**Issue by vtsaplin** [hlxsites/bitdefender#397]
**Tasks**

- [x] Create an Analytics report in Bitdefender org to capture data coming from WebSDK
- [x] Create and configure a Datastream
- [x] Load and configure `alloy.js`
- [x] Start sending events using WebSDK and a basic payload
