### ISSUE TITLE
Sticky nav bar

### ISSUE THREAD

**Issue by basecode** [hlxsites/bitdefender#6]
![Screenshot 2023-07-10 at 10 41 15](https://github.com/hlxsites/bitdefender/assets/143527/1715f7f2-6a49-41ef-be8a-f735c7a6817c)

**Tasks**
- [x] [Documentation](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/bitdefender/docs/blocks/sticky-navigation.docx?d=w3ad091f9adb04065ac5cac29a576e83f&csf=1&web=1&e=UAoecK)
- [x] [Test page ](http://localhost:3000/en-au/solutions/internet-security)
- [x] Sticky navigation menu implementation for desktop
- [x] Sticky navigation menu implementation for mobile
- [x] Scroll effect (see [discussion](https://cq-dev.slack.com/archives/C05EZA1LX1B/p1689258048552059?thread_ts=1689243896.519079&cid=C05EZA1LX1B))
- [x] Underline effect (desktop and mobile)
- [ ] Dark mode (if confirmed)
- [x] Select menu automatically when user scrolls
- [ ] Add action button on the right
