### ISSUE TITLE
Product cards

### ISSUE THREAD

**Issue by basecode** [hlxsites/bitdefender#7]
https://www.bitdefender.com.au/solutions/

Identify what cards exists on all pages https://adobe-dx-support.slack.com/archives/C05E0MH7FRV/p1688718296627479?thread_ts=1688123219.642389&cid=C05E0MH7FRV and document the variations.

Then start working to implement the different card variants with focus on CSS/JS. We don't know yet where the content will come from. Assuming from external API.

Example of documentation: https://github.com/hlxsites/mammotome/blob/main/docs/blocks/cards.md

**Card variations** 

Red-marked values come from the web service, the rest is content.

<img width="200" alt="Screenshot 2023-07-19 at 07 24 23" src="https://github.com/hlxsites/bitdefender/assets/1468264/dbe5d0e8-5c68-48cd-abf5-3de79417c4da">
<img width="200" alt="Screenshot 2023-07-19 at 07 25 26" src="https://github.com/hlxsites/bitdefender/assets/1468264/7dbf09f4-7ae0-4146-9bde-c9c1d2be3296">
<img width="200" alt="Screenshot 2023-07-19 at 07 21 47" src="https://github.com/hlxsites/bitdefender/assets/1468264/0515b0f8-ca62-48b4-b14e-00a7ab5493b8">

**Tasks**

- [x] Implement functionality for fetching data
- [x] Implement a block for rendering cards
- [ ] Propose new content structure to a customer
